[package]
name = "rmquickjs"
description = "High-level MicroQuickJS bindings for Rust"
version = "1.0.0"
edition = "2024"
readme = "../../README.md"
license = "MIT"
repository = "https://github.com/nuskey8/rmquickjs"
documentation = "https://docs.rs/rmquickjs"
keywords = ["mquickjs", "quickjs", "javascript"]
categories = ["api-bindings", "no-std"]

[dependencies]
rmquickjs-sys = { version = "1.0.0", path = "../rmquickjs-sys" }
